version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@rails/ujs"
    versions:
    - 6.1.1
    - 6.1.2
  - dependency-name: "@rails/actioncable"
    versions:
    - 6.1.1
    - 6.1.2
  - dependency-name: "@rails/activestorage"
    versions:
    - 6.1.1
    - 6.1.2
  - dependency-name: lodash
    versions:
    - 4.17.20
